INDIAN_DISTRICTS = [
    "Ariyalur", "Chengalpattu", "Chennai", "Coimbatore",
    "Cuddalore", "Dharmapuri", "Dindigul", "Erode",
    "Kallakurichi", "Kancheepuram", "Karur", "Krishnagiri",
    "Madurai", "Mayiladuthurai", "Nagapattinam", "Namakkal",
    "Nilgiris", "Perambalur", "Pudukkottai", "Ramanathapuram",
    "Ranipet", "Salem", "Sivaganga", "Tenkasi", "Thanjavur",
    "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli",
    "Tirupathur", "Tiruppur", "Tiruvallur", "Tiruvannamalai",
    "Tiruvarur", "Vellore", "Viluppuram", "Virudhunagar",
    # Add remaining states and districts below
    "Mumbai", "Pune", "Nagpur", "Thane", "Nashik",
    "Delhi", "New Delhi", "North Delhi", "South Delhi",
    "Bengaluru Urban", "Bengaluru Rural", "Mysuru", "Mangaluru",
    "Hyderabad", "Warangal", "Karimnagar", "Nizamabad",
    "Kolkata", "Howrah", "Darjeeling", "Siliguri",
    "Ahmedabad", "Surat", "Vadodara", "Rajkot",
    "Jaipur", "Jodhpur", "Udaipur", "Kota",
    "Lucknow", "Kanpur", "Varanasi", "Agra", "Allahabad",
    "Patna", "Gaya", "Muzaffarpur", "Bhagalpur",
    "Bhopal", "Indore", "Gwalior", "Jabalpur",
    "Bhubaneswar", "Cuttack", "Rourkela",
    "Guwahati", "Dibrugarh", "Silchar",
    "Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur",
    "Chandigarh", "Amritsar", "Ludhiana", "Jalandhar",
    "Dehradun", "Haridwar", "Nainital",
    "Ranchi", "Dhanbad", "Jamshedpur",
    "Raipur", "Bilaspur", "Durg",
    "Panaji", "North Goa", "South Goa",
    "Shimla", "Kangra", "Mandi",
    "Srinagar", "Jammu", "Leh",
    "Imphal", "Shillong", "Aizawl", "Kohima",
    "Agartala", "Itanagar", "Gangtok", "Daman", "Silvassa"
]
